#log
log:
  level: info

# Kafka 配置
kafka:
  brokers: "" # 环境变量 MOONX_KAFKA_HOSTS
  topic_trade: "web3_trade_events"
  topic_data: "web3_data_events"
  topic_balance: "web3_block_balance_events"
  topic_smart_trade: "web3_smart_trade_events"
  group_id: "web3_smart_consumer_dev"

# byd_rpc_url: http://byd-host:30032
# bsc_client_rawurl: http://nlb-vr27uf1tvi312e38ai.eu-central-1.nlb.aliyuncsslbintl.com:64021
# solana_client_rawurl: https://jadeite-greasily-xykrmnpgkw-dedicated.helius-rpc.com?api-key=90e3661e-4c5f-4e6b-af81-

byd_rpc_url: "" # 环境变量 BYDRPC
bsc_client_rawurl: "" # 环境变量 BSC_CLIENT_RAWURL
solana_client_rawurl: "" # 环境变量 SOLANA_CLIENT_RAWURL

# Redis 配置
redis:
  address: "" # 环境变量 MOONX_REDIS_ADDRESS
  password: "" # 环境变量 MOONX_REDIS_PWD
  db: 7
  db_metrics: 0
  db_price: 1

# PostgreSQL 配置
postgres:
  dsn: "" # 环境变量 MOONX_PG_DSN

# SelectDB 配置
selectdb:
  dsn: "" # 环境变量 MOONX_SELECTDB_DSN
  base_url: "" # 环境变量 MOONX_SELECTDB_BASE_URL
  database: "smart_money"
  username: "" # 环境变量 MOONX_SELECTDB_USERNAME
  password: "" # 环境变量 MOONX_SELECTDB_PASSWORD

# Elasticsearch 配置
elasticsearch:
  addresses: "" # 环境变量，多个用','分割 MOONX_ELASTICSEARCH_ADDRESSES
  username: "" # 环境变量 MOONX_ELASTICSEARCH_USERNAME
  password: "" # 环境变量 MOONX_ELASTICSEARCH_PASSWORD
  holdings_index_name: "web3_smart_holdings"
  wallets_index_name: "web3_smart_wallets"
  web3tokens_index_name: "web3_tokens"

moralis:
  base_url: "https://deep-index.moralis.io"
  gateway_url: "https://solana-gateway.moralis.io"
  api_key: "" # 环境变量 MOONX_MORALIS_API_KEY
  rate_limit: 120
  timeout: 30


lark:
  webhook: "" # 环境变量 MOONX_LARK_WEBHOOK

# smart-money worker
worker:
  worker_num: 16

# monitor
monitor:
  enable: true
  prometheus_addr: "0.0.0.0:8091"
